# version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: tanti-portfolio-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tanti
      POSTGRES_PASSWORD: randompassword11
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:
    name: tanti-portfolio-postgres-data

networks:
  app-network:
    driver: bridge